In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("housing.csv")

In [4]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [5]:
df.head(10)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386
5,80175.75416,4.988408,6.104512,4.04,26748.42842,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
6,64698.46343,6.025336,8.147760,3.41,60828.24909,1.502056e+06,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ..."
7,78394.33928,6.989780,6.620478,2.42,36516.35897,1.573937e+06,"972 Joyce Viaduct\nLake William, TN 17778-6483"
8,59927.66081,5.362126,6.393121,2.30,29387.39600,7.988695e+05,USS Gilbert\nFPO AA 20957
9,81885.92718,4.423672,8.167688,6.10,40149.96575,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025

In [6]:
df.head(15)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386
5,80175.75416,4.988408,6.104512,4.04,26748.42842,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
6,64698.46343,6.025336,8.147760,3.41,60828.24909,1.502056e+06,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ..."
7,78394.33928,6.989780,6.620478,2.42,36516.35897,1.573937e+06,"972 Joyce Viaduct\nLake William, TN 17778-6483"
8,59927.66081,5.362126,6.393121,2.30,29387.39600,7.988695e+05,USS Gilbert\nFPO AA 20957
9,81885.92718,4.423672,8.167688,6.10,40149.96575,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025
10,80527.47208,8.093513,5.042747,4.10,47224.35984,1.707046e+06,"6368 John Motorway Suite 700\nJanetbury, NM 26854"
11,50593.69550,4.496513,7.467627,4.49,34343.99189,6.637324e+05,"911 Castillo Park Apt. 717\nDavisborough, PW 7..."
12,39033.80924,7.671755,7.250029,3.10,39220.36147,1.042814e+06,"209 Natasha Stream Suite 961\nHuffmanland, NE ..."
13,73163.66344,6.919535,5.993188,2.27,32326.12314,1.291332e+06,"829 Welch Track Apt. 992\nNorth John, AR 26532..."
14,69391.38018,5.344776,8.406418,4.37,35521.29403,1.402818e+06,"PSC 5330, Box 4420\nAPO AP 08302"

In [7]:
df.shape

(5000, 7)

In [8]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   str
dtypes: float64(6), str(1)
memory usage: 499.6 KB

In [10]:
df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562390,5.322283,6.299250,3.140000,29403.928700,9.975771e+05
50%,68804.286405,5.970429,7.002902,4.050000,36199.406690,1.232669e+06
75%,75783.338665,6.650808,7.665871,4.490000,42861.290770,1.471210e+06
max,107701.748400,9.519088,10.759588,6.500000,69621.713380,2.469066e+06

In [11]:
df.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop("Address",axis=1)

In [14]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05

In [15]:
x= df.drop("Price",axis=1)

In [16]:
y = df["Price"]

In [17]:
print(x.head())
print(y.head())

   Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188
1       79248.64245             6.002900                   6.730821
2       61287.06718             5.865890                   8.512727
3       63345.24005             7.188236                   5.586729
4       59982.19723             5.040555                   7.839388

   Avg. Area Number of Bedrooms  Area Population
0                          4.09      23086.80050
1                          3.09      40173.07217
2                          5.13      36882.15940
3                          3.26      34310.24283
4                          4.23      26354.10947
0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: Price, dtype: float64

In [18]:
print(x.shape)
print(y.shape)

(5000, 5)
(5000,)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train , X_text, y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
print(X_train.shape)
print(X_text.shape)

print(y_train.shape)
print(y_test.shape)

(4000, 5)
(1000, 5)
(4000,)
(1000,)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()

In [25]:
model.fit(X_train,y_train)

LinearRegression()

In [26]:
y_pred = model.predict(X_text)

In [27]:
print(y_pred[:10])

[1308587.92718454 1237037.2295027  1243429.34023036 1228900.21368759
 1063320.90731602 1544058.05050095 1094774.70494254  833284.72338233
  788412.85579609 1469714.86611293]

In [28]:
comparison = pd.DataFrame({
    "Actual value":y_test.values,
    "predict values": y_pred
})
comparison.head(10)

   Actual value  predict values
0   1339096.077    1.308588e+06
1   1251794.179    1.237037e+06
2   1340094.966    1.243429e+06
3   1431507.623    1.228900e+06
4   1042373.524    1.063321e+06
5   1555320.500    1.544058e+06
6   1250882.292    1.094775e+06
7   1039380.722    8.332847e+05
8    832475.189    7.884129e+05
9   1420648.281    1.469715e+06

In [29]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print("MAE:",mae)

MAE: 80879.09722218334

In [30]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

MSE: 10089009299.499464

In [31]:
import numpy as np 
rmse = np.sqrt(mse)
print("RMSE:",rmse)

RMSE: 100444.06054864301

In [32]:
from sklearn.metrics import r2_score
r2= r2_score(y_test, y_pred)
print("R2 score:",r2)

R2 score: 0.9179971706985317

In [33]:
print(model.coef_)

print(model.intercept_)

[2.16522058e+01 1.64666481e+05 1.19624012e+05 2.44037761e+03
 1.52703134e+01]
-2635072.900916771

In [34]:
print(x.columns)

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population'],
      dtype='str')

In [35]:
for feature , coefficient in zip(x.columns, model.coef_):
    print(feature,":",coefficient)

Avg. Area Income : 21.65220576368143
Avg. Area House Age : 164666.48072042383
Avg. Area Number of Rooms : 119624.01223050474
Avg. Area Number of Bedrooms : 2440.37761154543
Area Population : 15.270313429966336

In [36]:
print(x.describe().loc[["min","max"]])

     Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
min       17796.63119             2.644304                   3.236194
max      107701.74840             9.519088                  10.759588

     Avg. Area Number of Bedrooms  Area Population
min                           2.0       172.610686
max                           6.5     69621.713380

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

In [39]:
X_train_scale = scaler.fit_transform(X_train)

In [40]:
X_text_scale = scaler.transform(X_text)

In [41]:
scaled_model = LinearRegression()
scaled_model.fit(X_train_scale,y_train)

LinearRegression()

In [42]:
y_pred_scaled = scaled_model.predict(X_text_scale)

In [43]:
r2_scale = r2_score(y_test, y_pred_scaled)
print("scaled model:",r2_scale)

scaled model: 0.9179971706985147

In [44]:
import joblib

In [45]:
joblib.dump(model, "house_price_model.pkl")

['house_price_model.pkl']

In [47]:
!streamlit --version

Streamlit, version 1.61.1

In [48]:
test_house = [[70000, 6, 7, 4, 35000]]

test_prediction = model.predict(test_house)

print(test_prediction)

[1250170.95297201]

c:\Users\muham\miniconda3\envs\first_env\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [49]:
print(model.coef_)
print(model.intercept_)

[2.16522058e+01 1.64666481e+05 1.19624012e+05 2.44037761e+03
 1.52703134e+01]
-2635072.900916771

In [50]:
print(model.predict([[70000, 6, 7, 4, 35000]]))

[1250170.95297201]

c:\Users\muham\miniconda3\envs\first_env\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(